version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/animate-scroll"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/character-counter"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/circles"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/counter"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/fractions"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/image-loader"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/maps"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/moving-type"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/notepad"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/oblique-strategies"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/observer"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/pixelate"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/rainbow"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/random-color"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/scroll-video"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/speech"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/squares"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/strobe"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/syntax"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/triangle"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/venn"
    schedule:
      interval: "daily"

