name: auto-merge

on: pull_request

jobs:
  auto-merge:
    timeout-minutes: 5

    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v2
      # - uses: ahmadnassri/action-dependabot-auto-merge@v2
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN || github.token }}

      - uses: hmarr/auto-approve-action@v2.0.0
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - uses: ahmadnassri/action-dependabot-auto-merge@v1
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        with:
          target: patch
          github-token: ${{ secrets.GH_TOKEN }}
